single-sms-endpoint=https://api2.tiaraconnect.io/api/messaging/sendsms
bulk-sms-endpoint=https://api2.tiaraconnect.io/api/messaging/sendbatch
check-account-balance-endpoint=https://api2.tiaraconnect.io/api/messaging/checkbalance
api-key=test-api-key
sender-id=SENDER-ID
read-timeout=10
connect-timeout=2